[book]
authors = ["James Parks"]
description = "Documenting my learning about UniFi"
language = "en"
multilingual = false
src = "src"
title = "About UniFi"

[output.html]
[output.linkcheck]  # enable the "mdbook-linkcheck" renderer